// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.bjsxt.hbase;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string dnum = 1;
    /**
     * <code>required string dnum = 1;</code>
     */
    boolean hasDnum();
    /**
     * <code>required string dnum = 1;</code>
     */
    java.lang.String getDnum();
    /**
     * <code>required string dnum = 1;</code>
     */
    com.google.protobuf.ByteString
        getDnumBytes();

    // required string length = 2;
    /**
     * <code>required string length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>required string length = 2;</code>
     */
    java.lang.String getLength();
    /**
     * <code>required string length = 2;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    // required string type = 3;
    /**
     * <code>required string type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string date = 4;
    /**
     * <code>required string date = 4;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 4;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code com.bjsxt.hbase.PhoneDetail}
   */
  public static final class PhoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements PhoneDetailOrBuilder {
    // Use PhoneDetail.newBuilder() to construct.
    private PhoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhoneDetail defaultInstance;
    public static PhoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              dnum_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              length_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              date_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bjsxt.hbase.Phone.PhoneDetail.class, com.bjsxt.hbase.Phone.PhoneDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<PhoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<PhoneDetail>() {
      public PhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string dnum = 1;
    public static final int DNUM_FIELD_NUMBER = 1;
    private java.lang.Object dnum_;
    /**
     * <code>required string dnum = 1;</code>
     */
    public boolean hasDnum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dnum = 1;</code>
     */
    public java.lang.String getDnum() {
      java.lang.Object ref = dnum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dnum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dnum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDnumBytes() {
      java.lang.Object ref = dnum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private java.lang.Object length_;
    /**
     * <code>required string length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string length = 2;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          length_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string length = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.Object type_;
    /**
     * <code>required string type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string date = 4;
    public static final int DATE_FIELD_NUMBER = 4;
    private java.lang.Object date_;
    /**
     * <code>required string date = 4;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string date = 4;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      dnum_ = "";
      length_ = "";
      type_ = "";
      date_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDnum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLengthBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDateBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLengthBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bjsxt.hbase.Phone.PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bjsxt.hbase.Phone.PhoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bjsxt.hbase.PhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bjsxt.hbase.Phone.PhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bjsxt.hbase.Phone.PhoneDetail.class, com.bjsxt.hbase.Phone.PhoneDetail.Builder.class);
      }

      // Construct using com.bjsxt.hbase.Phone.PhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dnum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
      }

      public com.bjsxt.hbase.Phone.PhoneDetail getDefaultInstanceForType() {
        return com.bjsxt.hbase.Phone.PhoneDetail.getDefaultInstance();
      }

      public com.bjsxt.hbase.Phone.PhoneDetail build() {
        com.bjsxt.hbase.Phone.PhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bjsxt.hbase.Phone.PhoneDetail buildPartial() {
        com.bjsxt.hbase.Phone.PhoneDetail result = new com.bjsxt.hbase.Phone.PhoneDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dnum_ = dnum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bjsxt.hbase.Phone.PhoneDetail) {
          return mergeFrom((com.bjsxt.hbase.Phone.PhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bjsxt.hbase.Phone.PhoneDetail other) {
        if (other == com.bjsxt.hbase.Phone.PhoneDetail.getDefaultInstance()) return this;
        if (other.hasDnum()) {
          bitField0_ |= 0x00000001;
          dnum_ = other.dnum_;
          onChanged();
        }
        if (other.hasLength()) {
          bitField0_ |= 0x00000002;
          length_ = other.length_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000008;
          date_ = other.date_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDnum()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bjsxt.hbase.Phone.PhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bjsxt.hbase.Phone.PhoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string dnum = 1;
      private java.lang.Object dnum_ = "";
      /**
       * <code>required string dnum = 1;</code>
       */
      public boolean hasDnum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public java.lang.String getDnum() {
        java.lang.Object ref = dnum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dnum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDnumBytes() {
        java.lang.Object ref = dnum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dnum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder setDnum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder clearDnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dnum_ = getDefaultInstance().getDnum();
        onChanged();
        return this;
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder setDnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }

      // required string length = 2;
      private java.lang.Object length_ = "";
      /**
       * <code>required string length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string length = 2;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string length = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string length = 2;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>required string length = 2;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }

      // required string type = 3;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      // required string date = 4;
      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 4;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string date = 4;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 4;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 4;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 4;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bjsxt.hbase.PhoneDetail)
    }

    static {
      defaultInstance = new PhoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bjsxt.hbase.PhoneDetail)
  }

  public interface dayPhoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    java.util.List<com.bjsxt.hbase.Phone.PhoneDetail> 
        getDayPhoneDetailList();
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    com.bjsxt.hbase.Phone.PhoneDetail getDayPhoneDetail(int index);
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    int getDayPhoneDetailCount();
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    java.util.List<? extends com.bjsxt.hbase.Phone.PhoneDetailOrBuilder> 
        getDayPhoneDetailOrBuilderList();
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    com.bjsxt.hbase.Phone.PhoneDetailOrBuilder getDayPhoneDetailOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.bjsxt.hbase.dayPhoneDetail}
   */
  public static final class dayPhoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements dayPhoneDetailOrBuilder {
    // Use dayPhoneDetail.newBuilder() to construct.
    private dayPhoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private dayPhoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final dayPhoneDetail defaultInstance;
    public static dayPhoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public dayPhoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private dayPhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dayPhoneDetail_ = new java.util.ArrayList<com.bjsxt.hbase.Phone.PhoneDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              dayPhoneDetail_.add(input.readMessage(com.bjsxt.hbase.Phone.PhoneDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dayPhoneDetail_ = java.util.Collections.unmodifiableList(dayPhoneDetail_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_dayPhoneDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_dayPhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bjsxt.hbase.Phone.dayPhoneDetail.class, com.bjsxt.hbase.Phone.dayPhoneDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<dayPhoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<dayPhoneDetail>() {
      public dayPhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dayPhoneDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<dayPhoneDetail> getParserForType() {
      return PARSER;
    }

    // repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;
    public static final int DAYPHONEDETAIL_FIELD_NUMBER = 1;
    private java.util.List<com.bjsxt.hbase.Phone.PhoneDetail> dayPhoneDetail_;
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    public java.util.List<com.bjsxt.hbase.Phone.PhoneDetail> getDayPhoneDetailList() {
      return dayPhoneDetail_;
    }
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    public java.util.List<? extends com.bjsxt.hbase.Phone.PhoneDetailOrBuilder> 
        getDayPhoneDetailOrBuilderList() {
      return dayPhoneDetail_;
    }
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    public int getDayPhoneDetailCount() {
      return dayPhoneDetail_.size();
    }
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    public com.bjsxt.hbase.Phone.PhoneDetail getDayPhoneDetail(int index) {
      return dayPhoneDetail_.get(index);
    }
    /**
     * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    public com.bjsxt.hbase.Phone.PhoneDetailOrBuilder getDayPhoneDetailOrBuilder(
        int index) {
      return dayPhoneDetail_.get(index);
    }

    private void initFields() {
      dayPhoneDetail_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDayPhoneDetailCount(); i++) {
        if (!getDayPhoneDetail(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dayPhoneDetail_.size(); i++) {
        output.writeMessage(1, dayPhoneDetail_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dayPhoneDetail_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dayPhoneDetail_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bjsxt.hbase.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bjsxt.hbase.Phone.dayPhoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bjsxt.hbase.dayPhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bjsxt.hbase.Phone.dayPhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_dayPhoneDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_dayPhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bjsxt.hbase.Phone.dayPhoneDetail.class, com.bjsxt.hbase.Phone.dayPhoneDetail.Builder.class);
      }

      // Construct using com.bjsxt.hbase.Phone.dayPhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDayPhoneDetailFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dayPhoneDetailBuilder_ == null) {
          dayPhoneDetail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dayPhoneDetailBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bjsxt.hbase.Phone.internal_static_com_bjsxt_hbase_dayPhoneDetail_descriptor;
      }

      public com.bjsxt.hbase.Phone.dayPhoneDetail getDefaultInstanceForType() {
        return com.bjsxt.hbase.Phone.dayPhoneDetail.getDefaultInstance();
      }

      public com.bjsxt.hbase.Phone.dayPhoneDetail build() {
        com.bjsxt.hbase.Phone.dayPhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bjsxt.hbase.Phone.dayPhoneDetail buildPartial() {
        com.bjsxt.hbase.Phone.dayPhoneDetail result = new com.bjsxt.hbase.Phone.dayPhoneDetail(this);
        int from_bitField0_ = bitField0_;
        if (dayPhoneDetailBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dayPhoneDetail_ = java.util.Collections.unmodifiableList(dayPhoneDetail_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dayPhoneDetail_ = dayPhoneDetail_;
        } else {
          result.dayPhoneDetail_ = dayPhoneDetailBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bjsxt.hbase.Phone.dayPhoneDetail) {
          return mergeFrom((com.bjsxt.hbase.Phone.dayPhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bjsxt.hbase.Phone.dayPhoneDetail other) {
        if (other == com.bjsxt.hbase.Phone.dayPhoneDetail.getDefaultInstance()) return this;
        if (dayPhoneDetailBuilder_ == null) {
          if (!other.dayPhoneDetail_.isEmpty()) {
            if (dayPhoneDetail_.isEmpty()) {
              dayPhoneDetail_ = other.dayPhoneDetail_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDayPhoneDetailIsMutable();
              dayPhoneDetail_.addAll(other.dayPhoneDetail_);
            }
            onChanged();
          }
        } else {
          if (!other.dayPhoneDetail_.isEmpty()) {
            if (dayPhoneDetailBuilder_.isEmpty()) {
              dayPhoneDetailBuilder_.dispose();
              dayPhoneDetailBuilder_ = null;
              dayPhoneDetail_ = other.dayPhoneDetail_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dayPhoneDetailBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDayPhoneDetailFieldBuilder() : null;
            } else {
              dayPhoneDetailBuilder_.addAllMessages(other.dayPhoneDetail_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDayPhoneDetailCount(); i++) {
          if (!getDayPhoneDetail(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bjsxt.hbase.Phone.dayPhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bjsxt.hbase.Phone.dayPhoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;
      private java.util.List<com.bjsxt.hbase.Phone.PhoneDetail> dayPhoneDetail_ =
        java.util.Collections.emptyList();
      private void ensureDayPhoneDetailIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dayPhoneDetail_ = new java.util.ArrayList<com.bjsxt.hbase.Phone.PhoneDetail>(dayPhoneDetail_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.bjsxt.hbase.Phone.PhoneDetail, com.bjsxt.hbase.Phone.PhoneDetail.Builder, com.bjsxt.hbase.Phone.PhoneDetailOrBuilder> dayPhoneDetailBuilder_;

      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public java.util.List<com.bjsxt.hbase.Phone.PhoneDetail> getDayPhoneDetailList() {
        if (dayPhoneDetailBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dayPhoneDetail_);
        } else {
          return dayPhoneDetailBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public int getDayPhoneDetailCount() {
        if (dayPhoneDetailBuilder_ == null) {
          return dayPhoneDetail_.size();
        } else {
          return dayPhoneDetailBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public com.bjsxt.hbase.Phone.PhoneDetail getDayPhoneDetail(int index) {
        if (dayPhoneDetailBuilder_ == null) {
          return dayPhoneDetail_.get(index);
        } else {
          return dayPhoneDetailBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder setDayPhoneDetail(
          int index, com.bjsxt.hbase.Phone.PhoneDetail value) {
        if (dayPhoneDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.set(index, value);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder setDayPhoneDetail(
          int index, com.bjsxt.hbase.Phone.PhoneDetail.Builder builderForValue) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.set(index, builderForValue.build());
          onChanged();
        } else {
          dayPhoneDetailBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(com.bjsxt.hbase.Phone.PhoneDetail value) {
        if (dayPhoneDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(value);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(
          int index, com.bjsxt.hbase.Phone.PhoneDetail value) {
        if (dayPhoneDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(index, value);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(
          com.bjsxt.hbase.Phone.PhoneDetail.Builder builderForValue) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(builderForValue.build());
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(
          int index, com.bjsxt.hbase.Phone.PhoneDetail.Builder builderForValue) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(index, builderForValue.build());
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addAllDayPhoneDetail(
          java.lang.Iterable<? extends com.bjsxt.hbase.Phone.PhoneDetail> values) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          super.addAll(values, dayPhoneDetail_);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder clearDayPhoneDetail() {
        if (dayPhoneDetailBuilder_ == null) {
          dayPhoneDetail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder removeDayPhoneDetail(int index) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.remove(index);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public com.bjsxt.hbase.Phone.PhoneDetail.Builder getDayPhoneDetailBuilder(
          int index) {
        return getDayPhoneDetailFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public com.bjsxt.hbase.Phone.PhoneDetailOrBuilder getDayPhoneDetailOrBuilder(
          int index) {
        if (dayPhoneDetailBuilder_ == null) {
          return dayPhoneDetail_.get(index);  } else {
          return dayPhoneDetailBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public java.util.List<? extends com.bjsxt.hbase.Phone.PhoneDetailOrBuilder> 
           getDayPhoneDetailOrBuilderList() {
        if (dayPhoneDetailBuilder_ != null) {
          return dayPhoneDetailBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dayPhoneDetail_);
        }
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public com.bjsxt.hbase.Phone.PhoneDetail.Builder addDayPhoneDetailBuilder() {
        return getDayPhoneDetailFieldBuilder().addBuilder(
            com.bjsxt.hbase.Phone.PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public com.bjsxt.hbase.Phone.PhoneDetail.Builder addDayPhoneDetailBuilder(
          int index) {
        return getDayPhoneDetailFieldBuilder().addBuilder(
            index, com.bjsxt.hbase.Phone.PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.bjsxt.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public java.util.List<com.bjsxt.hbase.Phone.PhoneDetail.Builder> 
           getDayPhoneDetailBuilderList() {
        return getDayPhoneDetailFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.bjsxt.hbase.Phone.PhoneDetail, com.bjsxt.hbase.Phone.PhoneDetail.Builder, com.bjsxt.hbase.Phone.PhoneDetailOrBuilder> 
          getDayPhoneDetailFieldBuilder() {
        if (dayPhoneDetailBuilder_ == null) {
          dayPhoneDetailBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.bjsxt.hbase.Phone.PhoneDetail, com.bjsxt.hbase.Phone.PhoneDetail.Builder, com.bjsxt.hbase.Phone.PhoneDetailOrBuilder>(
                  dayPhoneDetail_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dayPhoneDetail_ = null;
        }
        return dayPhoneDetailBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.bjsxt.hbase.dayPhoneDetail)
    }

    static {
      defaultInstance = new dayPhoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bjsxt.hbase.dayPhoneDetail)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bjsxt_hbase_PhoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bjsxt_hbase_dayPhoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bjsxt_hbase_dayPhoneDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013phone.proto\022\017com.bjsxt.hbase\"G\n\013PhoneD" +
      "etail\022\014\n\004dnum\030\001 \002(\t\022\016\n\006length\030\002 \002(\t\022\014\n\004t" +
      "ype\030\003 \002(\t\022\014\n\004date\030\004 \002(\t\"F\n\016dayPhoneDetai" +
      "l\0224\n\016dayPhoneDetail\030\001 \003(\0132\034.com.bjsxt.hb" +
      "ase.PhoneDetail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bjsxt_hbase_PhoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bjsxt_hbase_PhoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bjsxt_hbase_PhoneDetail_descriptor,
              new java.lang.String[] { "Dnum", "Length", "Type", "Date", });
          internal_static_com_bjsxt_hbase_dayPhoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bjsxt_hbase_dayPhoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bjsxt_hbase_dayPhoneDetail_descriptor,
              new java.lang.String[] { "DayPhoneDetail", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
